name: 'Ares: Push to status'

on:
  push:
    branches:
      - status
    paths:
      - '.github/workflows/ares-shared.yml'
      - '.github/workflows/ares-status.yml'
      - 'rust/**'

jobs:
  urbit:
    uses: ./.github/workflows/ares-shared.yml
